### PR TITLE
Put seccomp behind a flag

### LINKED ISSUE #69: Unable to run controller on RKE
We are on RKE with Kubernetes 1.21. When I install the helm chart I see the replicaset is stuck with 0 copies and this attached event:

```
% % k -n cert-manager describe rs cert-manager-trust-6796dcc8f5
Events:
  Type     Reason        Age                      From                   Message
  ----     ------        ----                     ----                   -------
  Warning  FailedCreate  4m32s (x548 over 5d20h)  replicaset-controller  Error creating: pods "cert-manager-trust-6796dcc8f5-" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/cert-manager-trust]: Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/cert-manager-trust]: Forbidden: seccomp may not be set]
```

and it does not appear that seccomp is a configurable field on a PSP. So I'm not sure how to allow the pod to define seccomp. Would the project be open to a flag for optionally hiding the securityContext option?

### PR DESCRIPTION
**Pull request by xrl**
Closes #69

### CODE REVIEW

**Review by SgtCoDFish — APPROVED** [review]
/lgtm
/approve
/ok-to-test

Simple and effective, my favourite type of PR!

Thanks so much!

**Comment by SgtCoDFish** [comment]
/test pull-trust-manager-verify

(Tests can be a little flakey - this is clearly a flake!)

**Comment by SgtCoDFish** [comment]
/test pull-trust-manager-verify

We'll get there eventually :joy:

**Comment by SgtCoDFish** [comment]
Ah, no, it's a legitimate failure and I just didn't look hard enough!

You'll need to run `make update-helm-docs` and commit the results; or else, I can do that for if you give me permission to push to your fork, or I can create my own PR and cherry pick your commit. Either way, I'll come back to this next week!

**Comment by inteon** [comment]
@SgtCoDFish I think we already had the permissions to push to the fork 😄

**Comment by xrl** [comment]
I can run the make command right now...

**Review by SgtCoDFish — APPROVED** [review]
/lgtm
/approve

I see no reason to hang around with this, might as well get it merged!

Thanks so much for raising this @xrl :rocket:

**Pull request merged**
