### PR TITLE
Allow configuring of the priorityClass

### PR DESCRIPTION
**Pull request by WatcherWhale**
This PR enables users to configure the `priorityClassName` field in the helm chart

### CODE REVIEW

**Review by erikgb — APPROVED** [review]
/lgtm

**Review by inteon — APPROVED** [review]
/approve

**Comment by wallrj** [comment]
@WatcherWhale  I've been writing some documentation explaining why to set priorityClassName when deploying cert-manager and what the value should be. Please read and feedback if you have time:
 * https://github.com/cert-manager/website/pull/1444

**Pull request merged**
