### PR TITLE
Bump version to v0.7.0-alpha.1

### PR DESCRIPTION
**Pull request by inteon**
preparing the v0.7.0-alpha.1 release

### CODE REVIEW

**Comment by erikgb** [comment]
I suggest we wait for https://github.com/cert-manager/trust-manager/pull/184. I have a feeling it's mergeable soon.

**Comment by erikgb** [comment]
I am not familiar with the release automation in this project, but

/lgtm

**Comment by inteon** [comment]
we should fix this flake: https://prow.build-infra.jetstack.net/view/gs/jetstack-logs/pr-logs/pull/cert-manager_trust-manager/186/pull-trust-manager-verify/1709976979819728896

**Pull request merged**
