### PR TITLE
Add optional resources block for init container

### PR DESCRIPTION
**Pull request by niklastanner**
Add optional resources block for the init container of the default package.

### CODE REVIEW

**Comment by SgtCoDFish** [comment]
/test pull-trust-manager-verify

(pod was killed during the test I think)

**Comment by SgtCoDFish** [comment]
Hey @niklastanner thanks for raising this (and sorry it took a while to look into)! It looks like your PR is falling foul of the new values schema that was added. Are you able to also update the schema?

**Comment by niklastanner** [comment]
@SgtCoDFish What do you mean by "update the schema"? It's the exact same schema already used by the main image. Building the template locally using `helm template` does generate a valid YAML file.

**Comment by SgtCoDFish** [comment]
My apologies - it looks like running `make generate` will solve the issue. I think the tests hiccuped when I looked - sorry!

**Comment by SgtCoDFish** [comment]
@niklastanner Are you able to run `make generate` locally quickly and commit the result? I might be able to squeeze this into the next trust-manager release this week if we're super quick

**Comment by SgtCoDFish** [comment]
@niklastanner I went ahead and did `make generate` in #316 just so we could include this in trust-manager v0.9.0

Thank you for your contribution, really appreciate you!

**Pull request closed without merging**
