### PR TITLE
Update a couple of instances of the old project name

### PR DESCRIPTION
**Pull request by SgtCoDFish**
Spotted these while working on something unrelated and couldn't help but shave the yak!

### CODE REVIEW

**Review by erikgb — APPROVED** [review]
/lgtm
/retest

Thanks Ash! 😊

**Comment by erikgb** [comment]
It seems like the Helm docs are not 100% up-to-date.

> Please run 'make -s update-helm-docs'

**Comment by inteon** [comment]
@SgtCoDFish I think you have an old dependency version, try removing your cached downloaded dependency binaries.

**Comment by SgtCoDFish** [comment]
> @SgtCoDFish I think you have an old dependency version, try removing your cached downloaded dependency binaries.

I know, I'm updating it so that it doesn't happen to anyone else!

**Comment by SgtCoDFish** [comment]
how has this merged with failing tests!? 😢

**Comment by erikgb** [comment]
> @SgtCoDFish I think you have an old dependency version, try removing your cached downloaded dependency binaries.

Is there any way to make Go detect this outdated situation?

**Comment by SgtCoDFish** [comment]
> Is there any way to make Go detect this outdated situation?

It's a problem with the makefile really, I'm gonna raise a PR which fixes it!

**Pull request merged**
