### PR TITLE
Add new optional registry and digest Helm values

### PR DESCRIPTION
**Pull request by erikgb**
Fixes https://github.com/cert-manager/trust-manager/issues/148

### CODE REVIEW

**Comment by JoshVanL** [comment]
Cheers!
/lgtm
/approve
/ok-to-test

**Comment by JoshVanL** [comment]
@erikgb looks like it needs a make helms doc update

**Comment by erikgb** [comment]
@JoshVanL Thanks, done now. I think I need to apply for a cert-manager org membership - to avoid waiting for the ok-test-label. PTAL

**Pull request merged**
