### PR TITLE
feat(helm): dual-stack cluster service configuration

### LINKED ISSUE #336: Helm chart support dual stack clusters
There is no way for me to set the ipFamilyPolicy to "preferDualStack" in the current helm chart

### PR DESCRIPTION
**Pull request by M0NsTeRRR**
Fix #336

### CODE REVIEW

**Comment by M0NsTeRRR** [comment]
Hello,

Apologies for the ping @inteon, it appears my PR has been overlooked for review. Is there something missing on my end? (I've noticed that some other PRs have been merged.)

Regards,

**Comment by M0NsTeRRR** [comment]
Hello,

@erikgb is it possible to get a review ?

Regards,

**Comment by erikgb** [comment]
@M0NsTeRRR Sorry for the long delay! The proposed changes looks good to me, but I am not familiar with dual-stack. You have extended the metrics service, would it make sense to have the same options on the webhook service or not?

**Comment by M0NsTeRRR** [comment]
Hello,

No worries!
Yes, it makes sense, I've missed it, it's in the last commit.
I can't tell you about other cluster network configurations, but IPv6 is growing, yes. Do people prefer single stack IPv6 over dual stack? I don't know. The only thing I can tell you is that I've contributed to other charts for this feature (cert-manager, CNPG, ArgoCD, Grafana, kube-prom-stack etc.), and nobody said it was niche, so I assume it isn't :D

**Comment by erikgb** [comment]
> Hello,
> 
> No worries! Yes, it makes sense, I've missed it, it's in the last commit. I can't tell you about other cluster network configurations, but IPv6 is growing, yes. Do people prefer single stack IPv6 over dual stack? I don't know. The only thing I can tell you is that I've contributed to other charts for this feature (cert-manager, CNPG, ArgoCD, Grafana, kube-prom-stack etc.), and nobody said it was niche, so I assume it isn't 😄

Ok, thanks! Did you forget to push? Please squash commits before merge. 🙏

**Comment by M0NsTeRRR** [comment]
> > Hello,
> > No worries! Yes, it makes sense, I've missed it, it's in the last commit. I can't tell you about other cluster network configurations, but IPv6 is growing, yes. Do people prefer single stack IPv6 over dual stack? I don't know. The only thing I can tell you is that I've contributed to other charts for this feature (cert-manager, CNPG, ArgoCD, Grafana, kube-prom-stack etc.), and nobody said it was niche, so I assume it isn't 😄
> 
> Ok, thanks! Did you forget to push? Please squash commits before merge. 🙏

Ah yes, my KeePassXC was locked

**Comment by erikgb** [comment]
Can you please modify the PR title? I don't have the required permissions yet. 😢 Something like:

````
feat(helm): dual-stack cluster service configuration
````

Dual-stack isn't added as a feature in trust-manger. 😉 And Helm.....

**Comment by M0NsTeRRR** [comment]
We should be good now :)

**Comment by erikgb** [comment]
Seems like you need to run `make generate-helm-schema` and maybe also `make generate-helm-docs` to fix CI.

**Comment by M0NsTeRRR** [comment]
It didn't change anything. I've looked into the CI logs, and it appears that `make generate-helm-schema` doesn't order properties properly for the linter, I've fixed the issue manually.

**Comment by erikgb** [comment]
> It didn't change anything. I've looked into the CI logs, and it appears that `make generate-helm-schema` doesn't order properties properly for the linter, I've fixed the issue manually.

Ok, thanks. Do you mind opening an issue with some additional information here: https://github.com/cert-manager/helm-tool/issues?

**Review by erikgb — APPROVED** [review]
Thanks, @M0NsTeRRR!

/lgtm
/approve

**Comment by M0NsTeRRR** [comment]
> > It didn't change anything. I've looked into the CI logs, and it appears that `make generate-helm-schema` doesn't order properties properly for the linter, I've fixed the issue manually.
> 
> Ok, thanks. Do you mind opening an issue with some additional information here: https://github.com/cert-manager/helm-tool/issues?

Yes sure :)

**Pull request merged**
