### PR TITLE
Feat: Add port naming for podMonitor support

### PR DESCRIPTION
**Pull request by noamgloberman0**
Add port naming for podMonitor support

### CODE REVIEW

**Comment by erikgb** [comment]
@noamgloberman0 This change should not be required to support `PodMonitor`, but I am guessing you don't want to use a deprecated field, ref. https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PodMetricsEndpoint.

/ok-to-test

**Comment by noamgloberman0** [comment]
hey @erikgb , could you approve this ?

**Comment by erikgb** [comment]
> hey @erikgb , could you review this ?

@noamgloberman0 Can you please:

1. Add a comment next to the container port names. I am a bit scared it might not be evident that eventual changes in this area can break for some users - since there are no references to these port names in trust-manager.
2. Squash this change into a single commit.

**Comment by noamgloberman0** [comment]
> > hey @erikgb , could you review this ?
> 
> @noamgloberman0 Can you please:
> 
> 1. Add a comment next to the container port names. I am a bit scared it might not be evident that eventual changes in this area can break for some users - since there are no references to these port names in trust-manager.
> 2. Squash all changes in this PR into a single commit.

done :)

**Comment by erikgb** [comment]
🚀 

/lgtm
/approve

**Pull request merged**
